### ISSUE TITLE
Error - Error in missing.control() : could not find function "missing.control"

### ISSUE THREAD

**Issue by David-Li0406** [BoevaLab/survboard#38]
Dear Authors,

Thank you for publishing the code and data. I installed the R environment following your instruction and when I tried to reproduce the experiment by running `bash scripts/sh/reproduce_experiments.sh`, there is an error occured: "Error in missing.control() : could not find function "missing.control".

As a beginner in R, I would like to ask about which packages should I install/ update to include this missing.control() function? Your answer would be really helpful to me :)

**Comment by David-Li0406** [comment]
I found missing.control() should be in the package prioritylasso. There is no error after I updated it from 0.2.5 to 0.3.0.

**Comment by dnwissel** [comment]
Hi David,

thanks for reaching out and your interest in SurvBoard!

Thank you for pointing this out, this likely means that we have a stale prioritylasso version in our lockfile; I will investigate this further once back from vacation.

Also just FWIW, `missing.control` specifies how PriorityLasso deals with samples for which some modalities may be missing (details here if curious: https://cran.r-project.org/web/packages/prioritylasso/vignettes/explanation_blockwise_missing.html).

Let us know if we can help further with anything! (will leave this open in the meantime)

**Comment by dnwissel** [comment]
Just manually bumped the version, thanks for letting us know!
